/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutProfileImport } from './routes/_mainLayout/profile'
import { Route as MainLayoutRecipeIndexImport } from './routes/_mainLayout/recipe.index'
import { Route as MainLayoutRecipeIdImport } from './routes/_mainLayout/recipe.$id'

// Create Virtual Routes

const MainLayoutIndexLazyImport = createFileRoute('/_mainLayout/')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexLazyRoute = MainLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/index.lazy').then((d) => d.Route),
)

const MainLayoutProfileRoute = MainLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutRecipeIndexRoute = MainLayoutRecipeIndexImport.update({
  path: '/recipe/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutRecipeIdRoute = MainLayoutRecipeIdImport.update({
  path: '/recipe/$id',
  getParentRoute: () => MainLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/profile': {
      preLoaderRoute: typeof MainLayoutProfileImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/': {
      preLoaderRoute: typeof MainLayoutIndexLazyImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/recipe/$id': {
      preLoaderRoute: typeof MainLayoutRecipeIdImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/recipe/': {
      preLoaderRoute: typeof MainLayoutRecipeIndexImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainLayoutRoute.addChildren([
    MainLayoutProfileRoute,
    MainLayoutIndexLazyRoute,
    MainLayoutRecipeIdRoute,
    MainLayoutRecipeIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
