/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutRecipeIndexImport } from './routes/_mainLayout/recipe.index'

// Create Virtual Routes

const MainLayoutIndexLazyImport = createFileRoute('/_mainLayout/')()
const MainLayoutRecipeIdLazyImport = createFileRoute(
  '/_mainLayout/recipe/$id',
)()

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexLazyRoute = MainLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/index.lazy').then((d) => d.Route),
)

const MainLayoutRecipeIndexRoute = MainLayoutRecipeIndexImport.update({
  path: '/recipe/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutRecipeIdLazyRoute = MainLayoutRecipeIdLazyImport.update({
  path: '/recipe/$id',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/recipe.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/': {
      preLoaderRoute: typeof MainLayoutIndexLazyImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/recipe/$id': {
      preLoaderRoute: typeof MainLayoutRecipeIdLazyImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/recipe/': {
      preLoaderRoute: typeof MainLayoutRecipeIndexImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainLayoutRoute.addChildren([
    MainLayoutIndexLazyRoute,
    MainLayoutRecipeIdLazyRoute,
    MainLayoutRecipeIndexRoute,
  ]),
])

/* prettier-ignore-end */
